// <auto-generated />
using Digital_World.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Digital_World.Migrations
{
    [DbContext(typeof(DigitalWorldContext))]
    partial class DigitalWorldContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Digital_World.Data.Entities.Account", b =>
                {
                    b.Property<uint>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("accountId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("AccountId"));

                    b.Property<long>("Cash")
                        .HasColumnType("bigint")
                        .HasColumnName("cash");

                    b.Property<int?>("Char1")
                        .HasColumnType("int")
                        .HasColumnName("char1");

                    b.Property<int?>("Char2")
                        .HasColumnType("int")
                        .HasColumnName("char2");

                    b.Property<int?>("Char3")
                        .HasColumnType("int")
                        .HasColumnName("char3");

                    b.Property<int?>("Char4")
                        .HasColumnType("int")
                        .HasColumnName("char4");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<int?>("LastChar")
                        .HasColumnType("int")
                        .HasColumnName("lastChar");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<int>("Premium")
                        .HasColumnType("int")
                        .HasColumnName("premium");

                    b.Property<string>("SecondPassword")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Silk")
                        .HasColumnType("int")
                        .HasColumnName("silk");

                    b.Property<uint?>("UniId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("uniId");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("AccountId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("acct", (string)null);
                });

            modelBuilder.Entity("Digital_World.Data.Entities.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("characterId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CharacterId"));

                    b.Property<uint>("AccountId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("accountId");

                    b.Property<byte[]>("Archive")
                        .HasColumnType("blob")
                        .HasColumnName("archive");

                    b.Property<string>("CharName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("charName");

                    b.Property<int>("Ds")
                        .HasColumnType("int")
                        .HasColumnName("ds");

                    b.Property<int>("Hp")
                        .HasColumnType("int")
                        .HasColumnName("hp");

                    b.Property<byte[]>("Inventory")
                        .HasColumnType("blob")
                        .HasColumnName("inventory");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("level");

                    b.Property<uint>("Map")
                        .HasColumnType("int unsigned")
                        .HasColumnName("map");

                    b.Property<ushort>("Model")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("model");

                    b.Property<long>("Money")
                        .HasColumnType("bigint")
                        .HasColumnName("money");

                    b.Property<int?>("Partner")
                        .HasColumnType("int")
                        .HasColumnName("partner");

                    b.Property<byte[]>("Warehouse")
                        .HasColumnType("blob")
                        .HasColumnName("warehouse");

                    b.Property<int>("X")
                        .HasColumnType("int")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("int")
                        .HasColumnName("y");

                    b.HasKey("CharacterId");

                    b.HasIndex("AccountId");

                    b.HasIndex("CharName")
                        .IsUnique();

                    b.ToTable("chars", (string)null);
                });

            modelBuilder.Entity("Digital_World.Data.Entities.DigimonEntity", b =>
                {
                    b.Property<int>("DigimonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("digimonId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DigimonId"));

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int")
                        .HasColumnName("characterId");

                    b.Property<uint>("DigiModel")
                        .HasColumnType("int unsigned")
                        .HasColumnName("digiModel");

                    b.Property<string>("DigiName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("digiName");

                    b.Property<byte>("DigiSlot")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("digiSlot");

                    b.Property<int>("Ds")
                        .HasColumnType("int")
                        .HasColumnName("ds");

                    b.Property<byte[]>("Evolutions")
                        .HasColumnType("blob")
                        .HasColumnName("evolutions");

                    b.Property<long>("Exp")
                        .HasColumnType("bigint")
                        .HasColumnName("exp");

                    b.Property<int>("Hp")
                        .HasColumnType("int")
                        .HasColumnName("hp");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("level");

                    b.Property<ushort>("Size")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("size");

                    b.HasKey("DigimonId");

                    b.HasIndex("CharacterId");

                    b.ToTable("digimon", (string)null);
                });

            modelBuilder.Entity("Digital_World.Data.Entities.Server", b =>
                {
                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("serverId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ServerId"));

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Port")
                        .HasColumnType("int")
                        .HasColumnName("port");

                    b.HasKey("ServerId");

                    b.ToTable("servers", (string)null);
                });

            modelBuilder.Entity("Digital_World.Data.Entities.Character", b =>
                {
                    b.HasOne("Digital_World.Data.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Digital_World.Data.Entities.DigimonEntity", b =>
                {
                    b.HasOne("Digital_World.Data.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
